myproject/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^pm_master/$', views.pmindex, name='pmindex'),
    url(r'^pm_master/add$', views.pmadd, name='pmadd'),
    url(r'^pm_master/create$', views.pmcreate, name='pmcreate'),
    url(r'^pm_master/edit/(?P<id>\d+)$', views.pmedit, name='pmedit'),
    url(r'^pm_master/edit/update/(?P<id>\d+)$', views.pmupdate, name='pmupdate'),
    url(r'^pm_master/delete/(?P<id>\d+)$', views.pmdelete, name='pmdelete'),

    url(r'^jobsheet_trace/$', views.sheetindex, name='sheetindex'),
    url(r'^jobsheet_trace/add/$', views.sheetadd, name='sheetadd'),
    url(r'^jobsheet_trace/add/create$', views.sheetcreate, name='sheetcreate'),
    url(r'^jobsheet_trace/edit/(?P<id>\d+)$', views.sheetedit, name='sheetedit'),
    url(r'^jobsheet_trace/edit/update/(?P<id>\d+)$', views.sheetupdate, name='sheetupdate'),
    url(r'^jobsheet_trace/delete/(?P<id>\d+)$', views.sheetdelete, name='sheetdelete'),

    url(r'^jobsheet/$', views.jobindex, name='jobindex'),
    url(r'^jobsheet/add/$', views.jobadd, name='jobadd'),
    url(r'^jobsheet/add/create$', views.jobcreate, name='jobcreate'),
    url(r'^jobsheet/edit/(?P<id>\d+)$', views.jobedit, name='jobedit'),
    url(r'^jobsheet/edit/update/(?P<id>\d+)$', views.jobupdate, name='jobupdate'),
    url(r'^jobsheet/delete/(?P<id>\d+)$', views.jobdelete, name='jobdelete'),


    url(r'^omr/$', views.omrindex, name='omrindex'),
    url(r'^omr/add$', views.omradd, name='omradd'),
    url(r'^omr/create$', views.omrcreate, name='omrcreate'),
    url(r'^omr/edit/(?P<id>\d+)$', views.omredit, name='omredit'),
    url(r'^omr/edit/update/(?P<id>\d+)$', views.omrupdate, name='omrupdate'),
    url(r'^omr/delete/(?P<id>\d+)$', views.omrdelete, name='omrdelete'),


    url(r'^Part_Tracker/$', views.partindex, name='partindex'),
    url(r'^Part_Tracker/add/$', views.partadd, name='partadd'),
    url(r'^Part_Tracker/add/create$', views.partcreate, name='partcreate'),
    url(r'^Part_Tracker/edit/(?P<id>\d+)$', views.partedit, name='partedit'),
    url(r'^Part_Tracker/edit/update/(?P<id>\d+)$', views.partupdate, name='partupdate'),
    url(r'^Part_Tracker/delete/(?P<id>\d+)$', views.partdelete, name='partdelete'),

    url(r'^pm_chart/$', views.chartindex, name='chartindex'),
    url(r'^pm_chart/add/$', views.chartadd, name='chartadd'),
    url(r'^pm_chart/add/create$', views.chartcreate, name='chartcreate'),
    url(r'^pm_chart/edit/(?P<id>\d+)$', views.chartedit, name='chartedit'),
    url(r'^pm_chart/edit/update/(?P<id>\d+)$', views.chartupdate, name='chartupdate'),
    url(r'^pm_chart/delete/(?P<id>\d+)$', views.chartdelete, name='chartdelete'),

    url(r'^dashboard/$', views.dashindex, name='dashindex'),
    url(r'^dashboard/add/$', views.dashadd, name='dashadd'),
    url(r'^dashboard/add/create$', views.dashcreate, name='dashcreate'),
    url(r'^dashboard/edit/(?P<id>\d+)$', views.dashedit, name='dashedit'),
    url(r'^dashboard/edit/update/(?P<id>\d+)$', views.dashupdate, name='dashupdate'),
    url(r'^dashboard/delete/(?P<id>\d+)$', views.dashdelete, name='dashdelete'),

    url(r'^consume/$', views.conindex, name='conindex'),
    url(r'^consume/add/$', views.conadd, name='conadd'),
    url(r'^consume/add/create$', views.concreate, name='concreate'),
    url(r'^consume/edit/(?P<id>\d+)$', views.conedit, name='conedit'),
    url(r'^consume/edit/update/(?P<id>\d+)$', views.conupdate, name='conupdate'),
    url(r'^consume/delete/(?P<id>\d+)$', views.condelete, name='condelete'),
]

myproject/myproject/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index_redirect, name='index_redirect'),
    url(r'^myapp/', include('myapp.urls')),
    url(r'^admin/', admin.site.urls),
]

myproject/myapp/models.py
from django.db import models
from django.core.validators import RegexValidator

alphaSpaces = RegexValidator(r'^[a-zA-Z ]+$','Only letters and spaces are allowed')
Numerics = RegexValidator(r'\+?\d[\d -]{8,12}\d','Please enter valid contact number')
Number = RegexValidator(r'^[0-9]\d*(\.\d+)?$','Please Enter only Numbers')
alphanumeric = RegexValidator(r'^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')

ORM_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Select_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Spare_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Nature_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
PO_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
DONE_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)



# Create your models here.
class Jobsheet_trace(models.Model):
		From_Date = models.DateField()
		To_Date = models.DateField()
		JobSheet_No = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])

class Jobsheet(models.Model):
		Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		JobSheet_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Type = models.CharField(max_length=100, validators=[alphanumeric])
		In_Date = models.DateField()
		Expt_Date = models.DateField()
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		Vehicle = models.CharField(max_length=100, validators=[alphanumeric])
		Out_Date = models.DateField()
		Trailor = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Additional_KM = models.CharField(max_length=100, validators=[alphanumeric])
		Owner = models.CharField(max_length=100, validators=[alphanumeric])
		Tyre_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Maintenance_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Total_KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])
		pendding_Remark = models.CharField(max_length=100, validators=[alphanumeric])
		Store = models.CharField(max_length=100, validators=[alphanumeric])
		Close_Date = models.DateField()
		JobSheet_No_List1 = models.CharField(verbose_name=("JobSheet No List"),max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		OutDate = models.DateField()
		KM_Reading1 = models.CharField(verbose_name=("KM Reading"), max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Check_list_Template = models.CharField(max_length=100, validators=[alphanumeric])

class OMR(models.Model):
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		OMR_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Date = models.DateField()
		OMR_No = models.CharField(max_length=100, validators=[alphanumeric])
		ORM_Type = models.CharField(max_length=100, choices=ORM_CHOICES,)
		Spare_Group = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		ORM_Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Place = models.CharField(max_length=100, validators=[alphanumeric])
		Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		On_Road_Date = models.DateField()
		Trip_Detail = models.CharField(max_length=100, validators=[alphanumeric])
		Approx_Amount = models.CharField(max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Comment = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Date = models.DateField()
		Verified_By = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Remarks = models.CharField(max_length=100, validators=[alphanumeric])

class Part_Tracker(models.Model):
		Type = models.CharField(max_length=100, choices=Select_CHOICES,)
		SNo = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_No = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_Date = models.DateField()
		CR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		DR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		Status = models.CharField(max_length=100, validators=[alphanumeric])
		Trail_Status = models.CharField(max_length=100, validators=[alphanumeric])
		Card_No = models.CharField(max_length=100, validators=[alphanumeric])
		Life = models.CharField(max_length=100, validators=[alphanumeric])
		S = models.BooleanField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Purchase_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		TP_Coast = models.CharField(max_length=100, validators=[alphanumeric])
		Scrap_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Est_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Reason = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Chart(models.Model):
		SNo = models.CharField(max_length=50, validators=[alphanumeric])
		Date = models.DateField()
		Inactive_Date = models.DateField()
		Class_Name = models.CharField(max_length=100, validators=[alphanumeric])
		PM_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Days = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Alert = models.CharField(max_length=100, validators=[alphanumeric])
		Map_Next_PM = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Master(models.Model):
		Preventive_list = models.CharField(max_length=100, validators=[alphanumeric])
		Preventive_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Spare_Group = models.CharField(max_length=100, choices=Spare_CHOICES,)
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Description = models.CharField(max_length=200, validators=[alphanumeric])


class Repair_Dashboard(models.Model):
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		Expected_Date = models.DateField()
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=200, validators=[alphanumeric])
		Driver_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		Supervisor_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		OutDate = models.DateField()

class Repair_Consume(models.Model):
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"),max_length=100,  validators=[alphanumeric])
		Supplier = models.CharField(max_length=100, validators=[alphanumeric])
		Consume_Search = models.CharField(max_length=100, validators=[alphanumeric])
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Supplier1 = models.CharField(verbose_name=("Supplier"), max_length=200, validators=[alphanumeric])
		PO_Type = models.CharField(max_length=100, choices=PO_CHOICES,)
		Narration =  models.CharField(max_length=100,  validators=[alphanumeric])
		Document_Date = models.DateField()
		Voucher_Date = models.DateField()
		Document_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vendor_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Expense_AC = models.CharField(max_length=100,  validators=[alphanumeric])
		Ref =  models.CharField(verbose_name=("Ref / PONo"), max_length=100,  validators=[alphanumeric])
		Labour_Code = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Qty = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Rate = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Amount = models.CharField(max_length=100,  validators=[alphanumeric])
		DoneBy = models.CharField(max_length=100, choices=DONE_CHOICES,)
		Labour_Remark = models.CharField(max_length=100,  validators=[alphanumeric])

myproject/myapp/templates/Part_Tracker/change.html
{% extends 'base.html' %}
{% block body %}
<h3 class="text-primary" style="text-align: center;">Part Tracker Registration</h3>
    <hr style="border-top:1px dotted #000;"/>
    {% if members4 %}
    <form method="POST" action="update/{{ members4.id }}">
        {% else %}
        <form class=""  action="create" method="POST">
    {% endif %}
        {% csrf_token %}
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Type" class="form-group"> <label for="id_Type" class="control-label  requiredField">
                Type<span class="asteriskField">*</span> </label> <div class="controls "> <select name="Type" class="select form-control" required id="id_Type"> <option value="Item1" {% if members4.Type == "Item1"%}
                     selected
                     {% endif %}
                     >Item1</option> 
                     <option value="Item2"
 {% if members.Type == "Item2"%}
                     selected
                     {% endif %}
                     >
                     Item2</option>

</select> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_SNo" class="form-group"> <label for="id_SNo" class="control-label  requiredField">
                SNo<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.SNo }}" name="SNo" maxlength="100" class="textinput textInput form-control" required id="id_SNo" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Doc_No" class="form-group"> <label for="id_Doc_No" class="control-label  requiredField">
                Doc No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Doc_No }}" name="Doc_No" maxlength="100" class="textinput textInput form-control" required id="id_Doc_No" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Doc_Date" class="form-group"> <label for="id_Doc_Date" class="control-label  requiredField">
                Doc Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members4.Doc_Date|date:'Y-m-d' }}" name="Doc_Date" class="datepicker dateinput form-control" required id="id_Doc_Date" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_CR_AC" class="form-group"> <label for="id_CR_AC" class="control-label  requiredField">
                CR AC<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.CR_AC }}" name="CR_AC" maxlength="100" class="textinput textInput form-control" required id="id_CR_AC" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_DR_AC" class="form-group"> <label for="id_DR_AC" class="control-label  requiredField">
                DR AC<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.DR_AC }}" name="DR_AC" maxlength="100" class="textinput textInput form-control" required id="id_DR_AC" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Status" class="form-group"> <label for="id_Status" class="control-label  requiredField">
                Status<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Status }}" name="Status" maxlength="100" class="textinput textInput form-control" required id="id_Status" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Trail_Status" class="form-group"> <label for="id_Trail_Status" class="control-label  requiredField">
                Trail Status<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Trail_Status }}" name="Trail_Status" maxlength="100" class="textinput textInput form-control" required id="id_Trail_Status" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Card_No" class="form-group"> <label for="id_Card_No" class="control-label  requiredField">
                Card No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Card_No }}" name="Card_No" maxlength="100" class="textinput textInput form-control" required id="id_Card_No" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Life" class="form-group"> <label for="id_Life" class="control-label  requiredField">
                Life<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Life }}" name="Life" maxlength="100" class="textinput textInput form-control" required id="id_Life" /> </div> </div> </div>
<div  
    class="col-md-3" > <div class="form-group"> <div id="div_id_S" class="checkbox"> <label for="id_S" class=""> <input type="checkbox" name="S" class="checkboxinput" id="id_S" />
                    S
                </label> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Vehicle_No" class="form-group"> <label for="id_Vehicle_No" class="control-label  requiredField">
                Vehicle No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Vehicle_No }}" name="Vehicle_No" maxlength="100" class="textinput textInput form-control" required id="id_Vehicle_No" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_KM_Reading" class="form-group"> <label for="id_KM_Reading" class="control-label  requiredField">
                KM Reading<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.KM_Reading }}" name="KM_Reading" maxlength="100" class="textinput textInput form-control" required id="id_KM_Reading" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_KM_Run" class="form-group"> <label for="id_KM_Run" class="control-label  requiredField">
                KM Run<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.KM_Run }}" name="KM_Run" maxlength="100" class="textinput textInput form-control" required id="id_KM_Run" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Purchase_Cost" class="form-group"> <label for="id_Purchase_Cost" class="control-label  requiredField">
                Purchase Cost<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Purchase_Cost }}" name="Purchase_Cost" maxlength="100" class="textinput textInput form-control" required id="id_Purchase_Cost" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_TP_Coast" class="form-group"> <label for="id_TP_Coast" class="control-label  requiredField">
                TP Coast<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.TP_Coast }}" name="TP_Coast" maxlength="100" class="textinput textInput form-control" required id="id_TP_Coast" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Scrap_Cost" class="form-group"> <label for="id_Scrap_Cost" class="control-label  requiredField">
                Scrap Cost<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Scrap_Cost }}" name="Scrap_Cost" maxlength="100" class="textinput textInput form-control" required id="id_Scrap_Cost" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Est_Cost" class="form-group"> <label for="id_Est_Cost" class="control-label  requiredField">
                Est Cost<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Est_Cost }}" name="Est_Cost" maxlength="100" class="textinput textInput form-control" required id="id_Est_Cost" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Reason" class="form-group"> <label for="id_Reason" class="control-label  requiredField">
                Reason<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members4.Reason }}" name="Reason" maxlength="100" class="textinput textInput form-control" required id="id_Reason" /> </div> </div> </div>

</div>
<!--         <div class="form-group">
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" value="{{ members4.firstname }}" required="required"/>
        </div>
        <div class="form-group">
            <label for="lastname">Lastname</label>
            <input type="text" name="lastname" value="{{ members.lastname }}" required="required"/>
        </div> -->
            {% if members4 %}
    <div class="form-group">
            <button type="submit" class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-edit"></span></button>
        </div>
        {% else %}
        <button type="submit" class="btn btn-sm btn-primary">save<span class="glyphicon glyphicon-plus" style="margin-left: 7px;"></span></button>
    {% endif %}
    <a class="btn btn-sm btn-danger" href="../">Cancel<span class="glyphicon glyphicon-remove" style="margin-left: 7px;"></span></a>
    </form>
{% endblock %}

myproject/myapp/templates/Part_Tracker/index.html
{% extends 'base.html' %}
{% block body %}
<style>
table {
        display: block;
        overflow-x: auto;
        white-space: nowrap;
    }
</style>
<h3 class="text-primary" style="text-align: center;">Part Tracker Registration</h3>
<hr style="border-top:1px dotted #000;"/>
<div class="container" style="text-align: center;">
    <a class="btn btn-sm btn-primary" href="add/{{ member2.id }}">New Entry<span class="glyphicon glyphicon-plus" style="margin-left: 7px;"></span></a>
</div>
<hr style="border-top:1px dotted #000;"/>
<table class="table table-bordered" id="example" class="display" cellspacing="0" width="100%">
    <thead class="alert-warning">
        <tr>
            <th>Type</th>
            <th>SNo</th>
            <th>Doc_No</th>
            <th>Doc_Date</th>
            <th>CR_AC</th>
            <th>DR_AC</th>
            <th>Status</th>
            <th>Trail_Status</th>
            <th>Card_No</th>
            <th>Life</th>
            <th>S</th>
            <th>Vehicle_No</th>
            <th>KM_Reading</th>
            <th>KM_Run</th>
            <th>Purchase_Cost</th>
            <th>TP_Coast</th>
            <th>Scrap_Cost</th>
            <th>Est_Cost</th>
            <th>Reason</th>    
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for member4 in members4 %}
        <tr>
            <td>{{ member4.Type }}</td>
            <td>{{ member4.SNo }}</td>
            <td>{{ member4.Doc_No }}</td>
            <td>{{ member4.Doc_Date }}</td>
            <td>{{ member4.CR_AC }}</td>
            <td>{{ member4.DR_AC }}</td>
            <td>{{ member4.Status }}</td>
            <td>{{ member4.Trail_Status }}</td>
            <td>{{ member4.Card_No }}</td>
            <td>{{ member4.Life }}</td>
            <td>{{ member4.S }}</td>
            <td>{{ member4.Vehicle_No }}</td>
            <td>{{ member4.KM_Reading }}</td>
            <td>{{ member4.KM_Run }}</td>
            <td>{{ member4.Purchase_Cost }}</td>
            <td>{{ member4.TP_Coast }}</td>
            <td>{{ member4.Scrap_Cost }}</td>
            <td>{{ member4.Est_Cost }}</td>
            <td>{{ member4.Reason }}</td>
            <td><center><a class="btn btn-sm btn-warning" href="edit/{{ member4.id }}"><span class="glyphicon glyphicon-edit"></span></a> <a class="btn btn-sm btn-danger" href="delete/{{ member4.id }}"><span class="glyphicon glyphicon-trash"></span></a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}