myproject/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^pm_master/$', views.pmindex, name='pmindex'),
    url(r'^pm_master/add$', views.pmadd, name='pmadd'),
    url(r'^pm_master/create$', views.pmcreate, name='pmcreate'),
    url(r'^pm_master/edit/(?P<id>\d+)$', views.pmedit, name='pmedit'),
    url(r'^pm_master/edit/update/(?P<id>\d+)$', views.pmupdate, name='pmupdate'),
    url(r'^pm_master/delete/(?P<id>\d+)$', views.pmdelete, name='pmdelete'),

    url(r'^jobsheet_trace/$', views.sheetindex, name='sheetindex'),
    url(r'^jobsheet_trace/add/$', views.sheetadd, name='sheetadd'),
    url(r'^jobsheet_trace/add/create$', views.sheetcreate, name='sheetcreate'),
    url(r'^jobsheet_trace/edit/(?P<id>\d+)$', views.sheetedit, name='sheetedit'),
    url(r'^jobsheet_trace/edit/update/(?P<id>\d+)$', views.sheetupdate, name='sheetupdate'),
    url(r'^jobsheet_trace/delete/(?P<id>\d+)$', views.sheetdelete, name='sheetdelete'),

    url(r'^jobsheet/$', views.jobindex, name='jobindex'),
    url(r'^jobsheet/add/$', views.jobadd, name='jobadd'),
    url(r'^jobsheet/add/create$', views.jobcreate, name='jobcreate'),
    url(r'^jobsheet/edit/(?P<id>\d+)$', views.jobedit, name='jobedit'),
    url(r'^jobsheet/edit/update/(?P<id>\d+)$', views.jobupdate, name='jobupdate'),
    url(r'^jobsheet/delete/(?P<id>\d+)$', views.jobdelete, name='jobdelete'),


    url(r'^omr/$', views.omrindex, name='omrindex'),
    url(r'^omr/add$', views.omradd, name='omradd'),
    url(r'^omr/create$', views.omrcreate, name='omrcreate'),
    url(r'^omr/edit/(?P<id>\d+)$', views.omredit, name='omredit'),
    url(r'^omr/edit/update/(?P<id>\d+)$', views.omrupdate, name='omrupdate'),
    url(r'^omr/delete/(?P<id>\d+)$', views.omrdelete, name='omrdelete'),


    url(r'^Part_Tracker/$', views.partindex, name='partindex'),
    url(r'^Part_Tracker/add/$', views.partadd, name='partadd'),
    url(r'^Part_Tracker/add/create$', views.partcreate, name='partcreate'),
    url(r'^Part_Tracker/edit/(?P<id>\d+)$', views.partedit, name='partedit'),
    url(r'^Part_Tracker/edit/update/(?P<id>\d+)$', views.partupdate, name='partupdate'),
    url(r'^Part_Tracker/delete/(?P<id>\d+)$', views.partdelete, name='partdelete'),

    url(r'^pm_chart/$', views.chartindex, name='chartindex'),
    url(r'^pm_chart/add/$', views.chartadd, name='chartadd'),
    url(r'^pm_chart/add/create$', views.chartcreate, name='chartcreate'),
    url(r'^pm_chart/edit/(?P<id>\d+)$', views.chartedit, name='chartedit'),
    url(r'^pm_chart/edit/update/(?P<id>\d+)$', views.chartupdate, name='chartupdate'),
    url(r'^pm_chart/delete/(?P<id>\d+)$', views.chartdelete, name='chartdelete'),

    url(r'^dashboard/$', views.dashindex, name='dashindex'),
    url(r'^dashboard/add/$', views.dashadd, name='dashadd'),
    url(r'^dashboard/add/create$', views.dashcreate, name='dashcreate'),
    url(r'^dashboard/edit/(?P<id>\d+)$', views.dashedit, name='dashedit'),
    url(r'^dashboard/edit/update/(?P<id>\d+)$', views.dashupdate, name='dashupdate'),
    url(r'^dashboard/delete/(?P<id>\d+)$', views.dashdelete, name='dashdelete'),

    url(r'^consume/$', views.conindex, name='conindex'),
    url(r'^consume/add/$', views.conadd, name='conadd'),
    url(r'^consume/add/create$', views.concreate, name='concreate'),
    url(r'^consume/edit/(?P<id>\d+)$', views.conedit, name='conedit'),
    url(r'^consume/edit/update/(?P<id>\d+)$', views.conupdate, name='conupdate'),
    url(r'^consume/delete/(?P<id>\d+)$', views.condelete, name='condelete'),
]

myproject/myproject/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index_redirect, name='index_redirect'),
    url(r'^myapp/', include('myapp.urls')),
    url(r'^admin/', admin.site.urls),
]

myproject/myapp/models.py
from django.db import models
from django.core.validators import RegexValidator

alphaSpaces = RegexValidator(r'^[a-zA-Z ]+$','Only letters and spaces are allowed')
Numerics = RegexValidator(r'\+?\d[\d -]{8,12}\d','Please enter valid contact number')
Number = RegexValidator(r'^[0-9]\d*(\.\d+)?$','Please Enter only Numbers')
alphanumeric = RegexValidator(r'^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')

ORM_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Select_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Spare_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Nature_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
PO_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
DONE_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)



# Create your models here.
class Jobsheet_trace(models.Model):
		From_Date = models.DateField()
		To_Date = models.DateField()
		JobSheet_No = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])

class Jobsheet(models.Model):
		Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		JobSheet_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Type = models.CharField(max_length=100, validators=[alphanumeric])
		In_Date = models.DateField()
		Expt_Date = models.DateField()
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		Vehicle = models.CharField(max_length=100, validators=[alphanumeric])
		Out_Date = models.DateField()
		Trailor = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Additional_KM = models.CharField(max_length=100, validators=[alphanumeric])
		Owner = models.CharField(max_length=100, validators=[alphanumeric])
		Tyre_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Maintenance_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Total_KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])
		pendding_Remark = models.CharField(max_length=100, validators=[alphanumeric])
		Store = models.CharField(max_length=100, validators=[alphanumeric])
		Close_Date = models.DateField()
		JobSheet_No_List1 = models.CharField(verbose_name=("JobSheet No List"),max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		OutDate = models.DateField()
		KM_Reading1 = models.CharField(verbose_name=("KM Reading"), max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Check_list_Template = models.CharField(max_length=100, validators=[alphanumeric])

class OMR(models.Model):
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		OMR_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Date = models.DateField()
		OMR_No = models.CharField(max_length=100, validators=[alphanumeric])
		ORM_Type = models.CharField(max_length=100, choices=ORM_CHOICES,)
		Spare_Group = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		ORM_Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Place = models.CharField(max_length=100, validators=[alphanumeric])
		Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		On_Road_Date = models.DateField()
		Trip_Detail = models.CharField(max_length=100, validators=[alphanumeric])
		Approx_Amount = models.CharField(max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Comment = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Date = models.DateField()
		Verified_By = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Remarks = models.CharField(max_length=100, validators=[alphanumeric])

class Part_Tracker(models.Model):
		Type = models.CharField(max_length=100, choices=Select_CHOICES,)
		SNo = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_No = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_Date = models.DateField()
		CR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		DR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		Status = models.CharField(max_length=100, validators=[alphanumeric])
		Trail_Status = models.CharField(max_length=100, validators=[alphanumeric])
		Card_No = models.CharField(max_length=100, validators=[alphanumeric])
		Life = models.CharField(max_length=100, validators=[alphanumeric])
		S = models.BooleanField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Purchase_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		TP_Coast = models.CharField(max_length=100, validators=[alphanumeric])
		Scrap_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Est_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Reason = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Chart(models.Model):
		SNo = models.CharField(max_length=50, validators=[alphanumeric])
		Date = models.DateField()
		Inactive_Date = models.DateField()
		Class_Name = models.CharField(max_length=100, validators=[alphanumeric])
		PM_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Days = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Alert = models.CharField(max_length=100, validators=[alphanumeric])
		Map_Next_PM = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Master(models.Model):
		Preventive_list = models.CharField(max_length=100, validators=[alphanumeric])
		Preventive_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Spare_Group = models.CharField(max_length=100, choices=Spare_CHOICES,)
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Description = models.CharField(max_length=200, validators=[alphanumeric])


class Repair_Dashboard(models.Model):
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		Expected_Date = models.DateField()
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=200, validators=[alphanumeric])
		Driver_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		Supervisor_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		OutDate = models.DateField()

class Repair_Consume(models.Model):
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"),max_length=100,  validators=[alphanumeric])
		Supplier = models.CharField(max_length=100, validators=[alphanumeric])
		Consume_Search = models.CharField(max_length=100, validators=[alphanumeric])
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Supplier1 = models.CharField(verbose_name=("Supplier"), max_length=200, validators=[alphanumeric])
		PO_Type = models.CharField(max_length=100, choices=PO_CHOICES,)
		Narration =  models.CharField(max_length=100,  validators=[alphanumeric])
		Document_Date = models.DateField()
		Voucher_Date = models.DateField()
		Document_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vendor_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Expense_AC = models.CharField(max_length=100,  validators=[alphanumeric])
		Ref =  models.CharField(verbose_name=("Ref / PONo"), max_length=100,  validators=[alphanumeric])
		Labour_Code = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Qty = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Rate = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Amount = models.CharField(max_length=100,  validators=[alphanumeric])
		DoneBy = models.CharField(max_length=100, choices=DONE_CHOICES,)
		Labour_Remark = models.CharField(max_length=100,  validators=[alphanumeric])

myproject/myapp/templates/omr/change.html
{% extends 'base.html' %}
{% block body %}
    {% if members3 %}
    <form method="POST" action="update/{{ members2.id }}">
        {% else %}
        <form   action="create" method="POST">
    {% endif %}
        {% csrf_token %}
<div  
    class="row" > <div  
    class="col-md-6" > <div id="div_id_Vehicle_No" class="form-group"> <label for="id_Vehicle_No" class="control-label  requiredField">
                Vehicle No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Vehicle_No }}" name="Vehicle_No" maxlength="50" class="textinput textInput form-control" required id="id_Vehicle_No" /> </div> </div> </div>
<div  
    class="col-md-6" > <div id="div_id_OMR_No_List" class="form-group"> <label for="id_OMR_No_List" class="control-label  requiredField">
                OMR No List<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.OMR_No_List }}" name="OMR_No_List" maxlength="100" class="textinput textInput form-control" required id="id_OMR_No_List" /> </div> </div> </div>

</div>
<div class="Basic Details" style="padding-top:1px;padding-bottom:1px;background-color:#d8d8d8;"><h3 style="text-align:center;margin-top:10px;">Basic Details </h3></div> <br> <div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Office_list" class="form-group"> <label for="id_Office_list" class="control-label  requiredField">
                Office list<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Office_list }}" name="Office_list" maxlength="100" class="textinput textInput form-control" required id="id_Office_list" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Date" class="form-group"> <label for="id_Date" class="control-label  requiredField">
                Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members3.Date }}" name="Date" class="datepicker dateinput form-control" required id="id_Date" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_OMR_No" class="form-group"> <label for="id_OMR_No" class="control-label  requiredField">
                OMR No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.OMR_No }}" name="OMR_No" maxlength="100" class="textinput textInput form-control" required id="id_OMR_No" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_ORM_Type" class="form-group"> <label for="id_ORM_Type" class="control-label  requiredField">
                ORM Type<span class="asteriskField">*</span> </label> <div class="controls "> <select name="ORM_Type" class="select form-control" required id="id_ORM_Type"> 
                     <option value="Item1" {% if members3.ORM_Type == "Item1"%}
                     selected
                     {% endif %}
                     >Item1</option> 
                     <option value="Item2"
 {% if members3.ORM_Type == "Item2"%}
                     selected
                     {% endif %}
                     >
                     Item2</option>

</select> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Spare_Group" class="form-group"> <label for="id_Spare_Group" class="control-label  requiredField">
                Spare Group<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Spare_Group }}" name="Spare_Group" maxlength="100" class="textinput textInput form-control" required id="id_Spare_Group" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Completion_Date" class="form-group"> <label for="id_Completion_Date" class="control-label  requiredField">
                Completion Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members3.Completion_Date }}" name="Completion_Date" class="datepicker dateinput form-control" required id="id_Completion_Date" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_ORM_Nature" class="form-group"> <label for="id_ORM_Nature" class="control-label  requiredField">
                ORM Nature<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.ORM_Nature }}" name="ORM_Nature" maxlength="100" class="textinput textInput form-control" required id="id_ORM_Nature" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Vehicle_No1" class="form-group"> <label for="id_Vehicle_No1" class="control-label  requiredField">
                Vehicle No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Vehicle_No1 }}" name="Vehicle_No1" maxlength="100" class="textinput textInput form-control" required id="id_Vehicle_No1" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Driver" class="form-group"> <label for="id_Driver" class="control-label  requiredField">
                Driver<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Driver }}" name="Driver" maxlength="100" class="textinput textInput form-control" required id="id_Driver" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Place" class="form-group"> <label for="id_Place" class="control-label  requiredField">
                Place<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Place }}" name="Place" maxlength="100" class="textinput textInput form-control" required id="id_Place" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Supervisor" class="form-group"> <label for="id_Supervisor" class="control-label  requiredField">
                Supervisor<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Supervisor }}" name="Supervisor" maxlength="100" class="textinput textInput form-control" required id="id_Supervisor" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_On_Road_Date" class="form-group"> <label for="id_On_Road_Date" class="control-label  requiredField">
                On Road Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members3.On_Road_Date }}" name="On_Road_Date" class="datepicker dateinput form-control" required id="id_On_Road_Date" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Trip_Detail" class="form-group"> <label for="id_Trip_Detail" class="control-label  requiredField">
                Trip Detail<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Trip_Detail }}" name="Trip_Detail" maxlength="100" class="textinput textInput form-control" required id="id_Trip_Detail" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Approx_Amount" class="form-group"> <label for="id_Approx_Amount" class="control-label  requiredField">
                Approx Amount<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Approx_Amount }}" name="Approx_Amount" maxlength="100" class="textinput textInput form-control" required id="id_Approx_Amount" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Remarks" class="form-group"> <label for="id_Remarks" class="control-label  requiredField">
                Remarks<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Remarks }}" name="Remarks" maxlength="100" class="textinput textInput form-control" required id="id_Remarks" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Comment" class="form-group"> <label for="id_Comment" class="control-label  requiredField">
                Comment<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Comment }}" name="Comment" maxlength="100" class="textinput textInput form-control" required id="id_Comment" /> </div> </div> </div>

</div>

<div class=" Details" style="padding-top:1px;padding-bottom:1px;background-color:#d8d8d8;"><h3 style="text-align:center;margin-top:10px;">Verification Details </h3></div> <br> <div  
    class="row" > <div  
    class="col-md-4" > <div id="div_id_Varification_Date" class="form-group"> <label for="id_Varification_Date" class="control-label  requiredField">
                Varification Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members3.Varification_Date }}" name="Varification_Date" class="datepicker dateinput form-control" required id="id_Varification_Date" /> </div> </div> </div>
<div  
    class="col-md-4" > <div id="div_id_Verified_By" class="form-group"> <label for="id_Verified_By" class="control-label  requiredField">
                Verified By<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Verified_By }}" name="Verified_By" maxlength="100" class="textinput textInput form-control" required id="id_Verified_By" /> </div> </div> </div>
<div  
    class="col-md-4" > <div id="div_id_Varification_Remarks" class="form-group"> <label for="id_Varification_Remarks" class="control-label  requiredField">
                Varification Remarks<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members3.Varification_Remarks }}" name="Varification_Remarks" maxlength="100" class="textinput textInput form-control" required id="id_Varification_Remarks" /> </div> </div> </div>

</div>
<!--         <div class="form-group">
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" value="{{ members3.firstname }}" required="required"/>
        </div>
        <div class="form-group">
            <label for="lastname">Lastname</label>
            <input type="text" name="lastname" value="{{ members.lastname }}" required="required"/>
        </div> -->
            {% if members3 %}
    <div class="form-group">
            <button type="submit" class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-edit"></span></button>
        </div>
        {% else %}
        <button type="submit" class="btn btn-sm btn-primary">Save<span class="glyphicon glyphicon-plus" style="margin-left: 7px;"></span></button>
    {% endif %}
    </form>
{% endblock %}

myproject/myapp/templates/omr/index.html
{% extends 'base.html' %}
{% block body %}
<style>
table {
        display: block;
        overflow-x: auto;
        white-space: nowrap;
    }
</style>
<h3 class="text-primary" style="text-align: center;">OMR Registration</h3>
<hr style="border-top:1px dotted #000;"/>
<table class="table table-bordered" id="example" class="display" cellspacing="0" width="100%">
    <thead class="alert-warning" style="overflow-x:auto;">
        <tr>
            <th>Vehicle_No</th>
            <th>OMR_No_List</th>
            <th>Office_list</th>
            <th>Date</th>
            <th>OMR_No</th>
            <th>ORM_Type</th>
            <th>Spare_Group</th>
            <th>Completion_Date</th>
            <th>ORM_Nature</th>
            <th>Vehicle_No</th>
            <th>Driver</th>
            <th>Place</th>
            <th>Supervisor</th>
            <th>On_Road_Date</th>
            <th>Trip_Detail</th>
            <th>Approx_Amount</th>
            <th>Remarks</th>
            <th>Comment</th>
            <th>Varification_Date</th>
            <th>Verified_By</th>
            <th>Varification_Remarks</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for member3 in members3 %}
        <tr>
            <td>{{ member3.Vehicle_No }}</td>
            <td>{{ member3.OMR_No_List }}</td>
            <td>{{ member3.Office_list }}</td>
            <td>{{ member3.Date }}</td>
            <td>{{ member3.OMR_No }}</td>
            <td>{{ member3.ORM_Type }}</td>
            <td>{{ member3.Spare_Group }}</td>
            <td>{{ member3.Completion_Date }}</td>
            <td>{{ member3.ORM_Nature }}</td>
            <td>{{ member3.Vehicle_No1 }}</td>
            <td>{{ member3.Driver }}</td>
            <td>{{ member3.Place }}</td>
            <td>{{ member3.Supervisor }}</td>
            <td>{{ member3.On_Road_Date }}</td>
            <td>{{ member3.Trip_Detail }}</td>
            <td>{{ member3.Approx_Amount }}</td>
            <td>{{ member3.Remarks }}</td>
            <td>{{ member3.Comment }}</td>
            <td>{{ member3.Varification_Date }}</td>
            <td>{{ member3.Verified_By }}</td>
            <td>{{ member3.Varification_Remarks }}</td>
            <td><center><a class="btn btn-sm btn-warning" href="edit/{{ member3.id }}"><span class="glyphicon glyphicon-edit"></span></a> 
                <a class="btn btn-sm btn-danger" href="delete/{{ member3.id }}"><span class="glyphicon glyphicon-trash"></span></a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}