myproject/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^pm_master/$', views.pmindex, name='pmindex'),
    url(r'^pm_master/add$', views.pmadd, name='pmadd'),
    url(r'^pm_master/create$', views.pmcreate, name='pmcreate'),
    url(r'^pm_master/edit/(?P<id>\d+)$', views.pmedit, name='pmedit'),
    url(r'^pm_master/edit/update/(?P<id>\d+)$', views.pmupdate, name='pmupdate'),
    url(r'^pm_master/delete/(?P<id>\d+)$', views.pmdelete, name='pmdelete'),

    url(r'^jobsheet_trace/$', views.sheetindex, name='sheetindex'),
    url(r'^jobsheet_trace/add/$', views.sheetadd, name='sheetadd'),
    url(r'^jobsheet_trace/add/create$', views.sheetcreate, name='sheetcreate'),
    url(r'^jobsheet_trace/edit/(?P<id>\d+)$', views.sheetedit, name='sheetedit'),
    url(r'^jobsheet_trace/edit/update/(?P<id>\d+)$', views.sheetupdate, name='sheetupdate'),
    url(r'^jobsheet_trace/delete/(?P<id>\d+)$', views.sheetdelete, name='sheetdelete'),

    url(r'^jobsheet/$', views.jobindex, name='jobindex'),
    url(r'^jobsheet/add/$', views.jobadd, name='jobadd'),
    url(r'^jobsheet/add/create$', views.jobcreate, name='jobcreate'),
    url(r'^jobsheet/edit/(?P<id>\d+)$', views.jobedit, name='jobedit'),
    url(r'^jobsheet/edit/update/(?P<id>\d+)$', views.jobupdate, name='jobupdate'),
    url(r'^jobsheet/delete/(?P<id>\d+)$', views.jobdelete, name='jobdelete'),


    url(r'^omr/$', views.omrindex, name='omrindex'),
    url(r'^omr/add$', views.omradd, name='omradd'),
    url(r'^omr/create$', views.omrcreate, name='omrcreate'),
    url(r'^omr/edit/(?P<id>\d+)$', views.omredit, name='omredit'),
    url(r'^omr/edit/update/(?P<id>\d+)$', views.omrupdate, name='omrupdate'),
    url(r'^omr/delete/(?P<id>\d+)$', views.omrdelete, name='omrdelete'),


    url(r'^Part_Tracker/$', views.partindex, name='partindex'),
    url(r'^Part_Tracker/add/$', views.partadd, name='partadd'),
    url(r'^Part_Tracker/add/create$', views.partcreate, name='partcreate'),
    url(r'^Part_Tracker/edit/(?P<id>\d+)$', views.partedit, name='partedit'),
    url(r'^Part_Tracker/edit/update/(?P<id>\d+)$', views.partupdate, name='partupdate'),
    url(r'^Part_Tracker/delete/(?P<id>\d+)$', views.partdelete, name='partdelete'),

    url(r'^pm_chart/$', views.chartindex, name='chartindex'),
    url(r'^pm_chart/add/$', views.chartadd, name='chartadd'),
    url(r'^pm_chart/add/create$', views.chartcreate, name='chartcreate'),
    url(r'^pm_chart/edit/(?P<id>\d+)$', views.chartedit, name='chartedit'),
    url(r'^pm_chart/edit/update/(?P<id>\d+)$', views.chartupdate, name='chartupdate'),
    url(r'^pm_chart/delete/(?P<id>\d+)$', views.chartdelete, name='chartdelete'),

    url(r'^dashboard/$', views.dashindex, name='dashindex'),
    url(r'^dashboard/add/$', views.dashadd, name='dashadd'),
    url(r'^dashboard/add/create$', views.dashcreate, name='dashcreate'),
    url(r'^dashboard/edit/(?P<id>\d+)$', views.dashedit, name='dashedit'),
    url(r'^dashboard/edit/update/(?P<id>\d+)$', views.dashupdate, name='dashupdate'),
    url(r'^dashboard/delete/(?P<id>\d+)$', views.dashdelete, name='dashdelete'),

    url(r'^consume/$', views.conindex, name='conindex'),
    url(r'^consume/add/$', views.conadd, name='conadd'),
    url(r'^consume/add/create$', views.concreate, name='concreate'),
    url(r'^consume/edit/(?P<id>\d+)$', views.conedit, name='conedit'),
    url(r'^consume/edit/update/(?P<id>\d+)$', views.conupdate, name='conupdate'),
    url(r'^consume/delete/(?P<id>\d+)$', views.condelete, name='condelete'),
]

myproject/myproject/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index_redirect, name='index_redirect'),
    url(r'^myapp/', include('myapp.urls')),
    url(r'^admin/', admin.site.urls),
]

myproject/myapp/models.py
from django.db import models
from django.core.validators import RegexValidator

alphaSpaces = RegexValidator(r'^[a-zA-Z ]+$','Only letters and spaces are allowed')
Numerics = RegexValidator(r'\+?\d[\d -]{8,12}\d','Please enter valid contact number')
Number = RegexValidator(r'^[0-9]\d*(\.\d+)?$','Please Enter only Numbers')
alphanumeric = RegexValidator(r'^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')

ORM_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Select_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Spare_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Nature_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
PO_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
DONE_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)



# Create your models here.
class Jobsheet_trace(models.Model):
		From_Date = models.DateField()
		To_Date = models.DateField()
		JobSheet_No = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])

class Jobsheet(models.Model):
		Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		JobSheet_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Type = models.CharField(max_length=100, validators=[alphanumeric])
		In_Date = models.DateField()
		Expt_Date = models.DateField()
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		Vehicle = models.CharField(max_length=100, validators=[alphanumeric])
		Out_Date = models.DateField()
		Trailor = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Additional_KM = models.CharField(max_length=100, validators=[alphanumeric])
		Owner = models.CharField(max_length=100, validators=[alphanumeric])
		Tyre_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Maintenance_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Total_KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])
		pendding_Remark = models.CharField(max_length=100, validators=[alphanumeric])
		Store = models.CharField(max_length=100, validators=[alphanumeric])
		Close_Date = models.DateField()
		JobSheet_No_List1 = models.CharField(verbose_name=("JobSheet No List"),max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		OutDate = models.DateField()
		KM_Reading1 = models.CharField(verbose_name=("KM Reading"), max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Check_list_Template = models.CharField(max_length=100, validators=[alphanumeric])

class OMR(models.Model):
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		OMR_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Date = models.DateField()
		OMR_No = models.CharField(max_length=100, validators=[alphanumeric])
		ORM_Type = models.CharField(max_length=100, choices=ORM_CHOICES,)
		Spare_Group = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		ORM_Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Place = models.CharField(max_length=100, validators=[alphanumeric])
		Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		On_Road_Date = models.DateField()
		Trip_Detail = models.CharField(max_length=100, validators=[alphanumeric])
		Approx_Amount = models.CharField(max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Comment = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Date = models.DateField()
		Verified_By = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Remarks = models.CharField(max_length=100, validators=[alphanumeric])

class Part_Tracker(models.Model):
		Type = models.CharField(max_length=100, choices=Select_CHOICES,)
		SNo = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_No = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_Date = models.DateField()
		CR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		DR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		Status = models.CharField(max_length=100, validators=[alphanumeric])
		Trail_Status = models.CharField(max_length=100, validators=[alphanumeric])
		Card_No = models.CharField(max_length=100, validators=[alphanumeric])
		Life = models.CharField(max_length=100, validators=[alphanumeric])
		S = models.BooleanField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Purchase_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		TP_Coast = models.CharField(max_length=100, validators=[alphanumeric])
		Scrap_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Est_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Reason = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Chart(models.Model):
		SNo = models.CharField(max_length=50, validators=[alphanumeric])
		Date = models.DateField()
		Inactive_Date = models.DateField()
		Class_Name = models.CharField(max_length=100, validators=[alphanumeric])
		PM_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Days = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Alert = models.CharField(max_length=100, validators=[alphanumeric])
		Map_Next_PM = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Master(models.Model):
		Preventive_list = models.CharField(max_length=100, validators=[alphanumeric])
		Preventive_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Spare_Group = models.CharField(max_length=100, choices=Spare_CHOICES,)
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Description = models.CharField(max_length=200, validators=[alphanumeric])


class Repair_Dashboard(models.Model):
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		Expected_Date = models.DateField()
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=200, validators=[alphanumeric])
		Driver_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		Supervisor_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		OutDate = models.DateField()

class Repair_Consume(models.Model):
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"),max_length=100,  validators=[alphanumeric])
		Supplier = models.CharField(max_length=100, validators=[alphanumeric])
		Consume_Search = models.CharField(max_length=100, validators=[alphanumeric])
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Supplier1 = models.CharField(verbose_name=("Supplier"), max_length=200, validators=[alphanumeric])
		PO_Type = models.CharField(max_length=100, choices=PO_CHOICES,)
		Narration =  models.CharField(max_length=100,  validators=[alphanumeric])
		Document_Date = models.DateField()
		Voucher_Date = models.DateField()
		Document_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vendor_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Expense_AC = models.CharField(max_length=100,  validators=[alphanumeric])
		Ref =  models.CharField(verbose_name=("Ref / PONo"), max_length=100,  validators=[alphanumeric])
		Labour_Code = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Qty = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Rate = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Amount = models.CharField(max_length=100,  validators=[alphanumeric])
		DoneBy = models.CharField(max_length=100, choices=DONE_CHOICES,)
		Labour_Remark = models.CharField(max_length=100,  validators=[alphanumeric])

myproject/myapp/templates/consume/change.html
    {% extends 'base.html' %}
    {% block body %}
    <h3 class="text-primary" style="text-align: center;">Repair Consume Registration</h3>
<hr style="border-top:1px dotted #000;"/>
        {% if members7 %}
        <form method="POST" action="update/{{ members7.id }}">
            {% else %}
            <form   action="create" method="POST">
        {% endif %}
            {% csrf_token %}
    <div  
        class="row" > <div  
        class="col-md-3" > <div id="div_id_Nature" class="form-group"> <label for="id_Nature" class="control-label  requiredField">
                    Nature<span class="asteriskField">*</span> </label> <div class="controls "> <select name="Nature" class="select form-control" required id="id_Nature">
                        <option value="Item1" {% if members7.Nature == "Item1"%}
                     selected
                     {% endif %}
                     >Item1</option> 
                     <option value="Item2"
 {% if members7.Nature == "Item2"%}
                     selected
                     {% endif %}
                     >
                     Item2</option>

    </select> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Vehicle_No1" class="form-group"> <label for="id_Vehicle_No" class="control-label  requiredField">
                    Vehicle No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Vehicle_No1 }}" name="Vehicle_No1" maxlength="100" class="textinput textInput form-control" required id="id_Vehicle_No1" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Supplier" class="form-group"> <label for="id_Supplier" class="control-label  requiredField">
                    Supplier<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Supplier }}" name="Supplier" maxlength="100" class="textinput textInput form-control" required id="id_Supplier" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Consume_Search" class="form-group"> <label for="id_Consume_Search" class="control-label  requiredField">
                    Consume Search<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Consume_Search }}" name="Consume_Search" maxlength="100" class="textinput textInput form-control" required id="id_Consume_Search" /> </div> </div> </div>

    </div>
    <div class="Basic Details" style="padding-top:1px;padding-bottom:1px;background-color:#d8d8d8;"><h3 style="text-align:center;margin-top:10px;">Basic Details </h3></div> <br> <div  
        class="row" > <div  
        class="col-md-3" > <div id="div_id_Office" class="form-group"> <label for="id_Office" class="control-label  requiredField">
                    Office<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Office }}" name="Office" maxlength="100" class="textinput textInput form-control" required id="id_Office" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Supplier1" class="form-group"> <label for="id_Supplier1" class="control-label  requiredField">
                    Supplier<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Supplier1 }}" name="Supplier1" maxlength="200" class="textinput textInput form-control" required id="id_Supplier1" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_PO_Type" class="form-group"> <label for="id_PO_Type" class="control-label  requiredField">
                    PO Type<span class="asteriskField">*</span> </label> <div class="controls "> <select name="PO_Type" class="select form-control" required id="id_PO_Type"> 
                     <option value="Item1" {% if members7.PO_Type == "Item1"%}
                     selected
                     {% endif %}
                     >Item1</option> 
                     <option value="Item2"
 {% if members7.PO_Type == "Item2"%}
                     selected
                     {% endif %}
                     >
                     Item2</option>

    </select> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Narration" class="form-group"> <label for="id_Narration" class="control-label  requiredField">
                    Narration<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Narration }}" name="Narration" maxlength="100" class="textinput textInput form-control" required id="id_Narration" /> </div> </div> </div>

    </div>
    <div  
        class="row" > <div  
        class="col-md-3" > <div id="div_id_Document_Date" class="form-group"> <label for="id_Document_Date" class="control-label  requiredField">
                    Document Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members7.Document_Date|date:'Y-m-d' }}" name="Document_Date" class="datepicker dateinput form-control" required id="id_Document_Date" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Voucher_Date" class="form-group"> <label for="id_Voucher_Date" class="control-label  requiredField">
                    Voucher Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members7.Voucher_Date|date:'Y-m-d' }}" name="Voucher_Date" class="datepicker dateinput form-control" required id="id_Voucher_Date" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Document_No" class="form-group"> <label for="id_Document_No" class="control-label  requiredField">
                    Document No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Document_No }}" name="Document_No" maxlength="100" class="textinput textInput form-control" required id="id_Document_No" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Vendor_No" class="form-group"> <label for="id_Vendor_No" class="control-label  requiredField">
                    Vendor No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Vendor_No }}" name="Vendor_No" maxlength="100" class="textinput textInput form-control" required id="id_Vendor_No" /> </div> </div> </div>

    </div>
    <div  
        class="row" > <div  
        class="col-md-3" > <div id="div_id_Vehicle_No" class="form-group"> <label for="id_Vehicle_No" class="control-label  requiredField">
                    Vehicle No<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Vehicle_No }}" name="Vehicle_No" maxlength="100" class="textinput textInput form-control form-control" required id="id_Vehicle_No" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Expense_AC" class="form-group"> <label for="id_Expense_AC" class="control-label  requiredField">
                    Expense AC<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Expense_AC }}" name="Expense_AC" maxlength="100" class="textinput textInput form-control" required id="id_Expense_AC" /> </div> </div> </div>

    </div>
    <div class=" Details" style="padding-top:1px;padding-bottom:1px;background-color:#d8d8d8;"><h3 style="text-align:center;margin-top:10px;">Labour Details </h3></div> <br> <div  
        class="row" > <div  
        class="col-md-3" > <div id="div_id_Ref" class="form-group"> <label for="id_Ref" class="control-label  requiredField">
                    Ref / PONo<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Ref }}" name="Ref" maxlength="100" class="textinput textInput form-control" required id="id_Ref" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Labour_Code" class="form-group"> <label for="id_Labour_Code" class="control-label  requiredField">
                    Labour Code<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Labour_Code }}" name="Labour_Code" maxlength="100" class="textinput textInput form-control" required id="id_Labour_Code" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Labour_Qty" class="form-group"> <label for="id_Labour_Qty" class="control-label  requiredField">
                    Labour Qty<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Labour_Qty }}" name="Labour_Qty" maxlength="100" class="textinput textInput form-control" required id="id_Labour_Qty" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Labour_Rate" class="form-group"> <label for="id_Labour_Rate" class="control-label  requiredField">
                    Labour Rate<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Labour_Rate }}" name="Labour_Rate" maxlength="100" class="textinput textInput form-control" required id="id_Labour_Rate" /> </div> </div> </div>

    </div>
    <div  
        class="row" > <div  
        class="col-md-3" > <div id="div_id_Labour_Amount" class="form-group"> <label for="id_Labour_Amount" class="control-label  requiredField">
                    Labour Amount<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Labour_Amount }}" name="Labour_Amount" maxlength="100" class="textinput textInput form-control" required id="id_Labour_Amount" /> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_DoneBy" class="form-group"> <label for="id_DoneBy" class="control-label  requiredField">
                    DoneBy<span class="asteriskField">*</span> </label> <div class="controls "> <select name="DoneBy" class="select form-control" required id="id_DoneBy"> 
                        <option value="Item1" {% if members7.DoneBy == "Item1"%}
                     selected
                     {% endif %}
                     >Item1</option> 
                     <option value="Item2"
 {% if members7.DoneBy == "Item2"%}
                     selected
                     {% endif %}
                     >
                     Item2</option>

    </select> </div> </div> </div>
    <div  
        class="col-md-3" > <div id="div_id_Labour_Remark" class="form-group"> <label for="id_Labour_Remark" class="control-label  requiredField">
                    Labour Remark<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members7.Labour_Remark }}" name="Labour_Remark" maxlength="100" class="textinput textInput form-control" required id="id_Labour_Remark" /> </div> </div> </div>

    </div>
                {% if members7 %}
        <div class="form-group">
                <button type="submit" class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-edit"></span></button>
            </div>
            {% else %}
            <button type="submit" class="btn btn-sm btn-primary">Save<span class="glyphicon glyphicon-plus" style="margin-left: 7px;"></span></button>
        {% endif %}
        <a class="btn btn-sm btn-danger" href="../">Cancel<span class="glyphicon glyphicon-remove" style="margin-left: 7px;"></span></a>
        </form>
    {% endblock %}

myproject/myapp/templates/consume/index.html
{% extends 'base.html' %}
{% block body %}
<style>
table {
        display: block;
        overflow-x: auto;
        white-space: nowrap;
    }
</style>
<h3 class="text-primary" style="text-align: center;">Repair Consume Registration</h3>
<hr style="border-top:1px dotted #000;"/>
<div class="container" style="text-align: center;">
    <a class="btn btn-sm btn-primary" href="add">New Entry<span class="glyphicon glyphicon-plus" style="margin-left: 7px;"></span></a>
</div>
<hr style="border-top:1px dotted #000;"/>
<table class="table table-bordered" id="example" class="display" cellspacing="0" width="100%">
    <thead class="alert-warning" style="overflow-x:auto;">
        <tr>
            <th>Nature</th>
            <th>Vehicle_No1</th>
            <th>Supplier</th>
            <th>Consume_Search</th>
            <th>Office</th>
            <th>Supplier1</th>
            <th>PO_Type</th>
            <th>Narration</th>
            <th>Document_Date</th>
            <th>Voucher_Date</th>
            <th>Document_No</th>
            <th>Vendor_No</th>
            <th>Vehicle_No</th>
            <th>Expense_AC</th>
            <th>Ref</th>
            <th>Labour_Code</th>
            <th>Labour_Qty</th>
            <th>Labour_Rate</th>
            <th>Labour_Amount</th>
            <th>DoneBy</th>
            <th>Labour_Remark</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for member7 in members7 %}
        <tr>
            <td>{{ member3.Nature }}</td>
            <td>{{ member3.Vehicle_No1 }}</td>
            <td>{{ member3.Supplier }}</td>
            <td>{{ member3.Consume_Search }}</td>
            <td>{{ member3.Office }}</td>
            <td>{{ member3.Supplier1 }}</td>
            <td>{{ member3.PO_Type }}</td>
            <td>{{ member3.Narration }}</td>
            <td>{{ member3.Document_Date }}</td>
            <td>{{ member3.Voucher_Date }}</td>
            <td>{{ member3.Document_No }}</td>
            <td>{{ member3.Vendor_No }}</td>
            <td>{{ member3.Vehicle_No }}</td>
            <td>{{ member3.Expense_AC }}</td>
            <td>{{ member3.Ref }}</td>
            <td>{{ member3.Labour_Code }}</td>
            <td>{{ member3.Labour_Qty }}</td>
            <td>{{ member3.Labour_Rate }}</td>
            <td>{{ member3.Labour_Amount }}</td>
            <td>{{ member3.DoneBy }}</td>
            <td>{{ member3.Labour_Remark }}</td>
            <td><center><a class="btn btn-sm btn-warning" href="edit/{{ member7.id }}"><span class="glyphicon glyphicon-edit"></span></a> 
                <a class="btn btn-sm btn-danger" href="delete/{{ member7.id }}"><span class="glyphicon glyphicon-trash"></span></a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}