myproject/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^pm_master/$', views.pmindex, name='pmindex'),
    url(r'^pm_master/add$', views.pmadd, name='pmadd'),
    url(r'^pm_master/create$', views.pmcreate, name='pmcreate'),
    url(r'^pm_master/edit/(?P<id>\d+)$', views.pmedit, name='pmedit'),
    url(r'^pm_master/edit/update/(?P<id>\d+)$', views.pmupdate, name='pmupdate'),
    url(r'^pm_master/delete/(?P<id>\d+)$', views.pmdelete, name='pmdelete'),

    url(r'^jobsheet_trace/$', views.sheetindex, name='sheetindex'),
    url(r'^jobsheet_trace/add/$', views.sheetadd, name='sheetadd'),
    url(r'^jobsheet_trace/add/create$', views.sheetcreate, name='sheetcreate'),
    url(r'^jobsheet_trace/edit/(?P<id>\d+)$', views.sheetedit, name='sheetedit'),
    url(r'^jobsheet_trace/edit/update/(?P<id>\d+)$', views.sheetupdate, name='sheetupdate'),
    url(r'^jobsheet_trace/delete/(?P<id>\d+)$', views.sheetdelete, name='sheetdelete'),

    url(r'^jobsheet/$', views.jobindex, name='jobindex'),
    url(r'^jobsheet/add/$', views.jobadd, name='jobadd'),
    url(r'^jobsheet/add/create$', views.jobcreate, name='jobcreate'),
    url(r'^jobsheet/edit/(?P<id>\d+)$', views.jobedit, name='jobedit'),
    url(r'^jobsheet/edit/update/(?P<id>\d+)$', views.jobupdate, name='jobupdate'),
    url(r'^jobsheet/delete/(?P<id>\d+)$', views.jobdelete, name='jobdelete'),


    url(r'^omr/$', views.omrindex, name='omrindex'),
    url(r'^omr/add$', views.omradd, name='omradd'),
    url(r'^omr/create$', views.omrcreate, name='omrcreate'),
    url(r'^omr/edit/(?P<id>\d+)$', views.omredit, name='omredit'),
    url(r'^omr/edit/update/(?P<id>\d+)$', views.omrupdate, name='omrupdate'),
    url(r'^omr/delete/(?P<id>\d+)$', views.omrdelete, name='omrdelete'),


    url(r'^Part_Tracker/$', views.partindex, name='partindex'),
    url(r'^Part_Tracker/add/$', views.partadd, name='partadd'),
    url(r'^Part_Tracker/add/create$', views.partcreate, name='partcreate'),
    url(r'^Part_Tracker/edit/(?P<id>\d+)$', views.partedit, name='partedit'),
    url(r'^Part_Tracker/edit/update/(?P<id>\d+)$', views.partupdate, name='partupdate'),
    url(r'^Part_Tracker/delete/(?P<id>\d+)$', views.partdelete, name='partdelete'),

    url(r'^pm_chart/$', views.chartindex, name='chartindex'),
    url(r'^pm_chart/add/$', views.chartadd, name='chartadd'),
    url(r'^pm_chart/add/create$', views.chartcreate, name='chartcreate'),
    url(r'^pm_chart/edit/(?P<id>\d+)$', views.chartedit, name='chartedit'),
    url(r'^pm_chart/edit/update/(?P<id>\d+)$', views.chartupdate, name='chartupdate'),
    url(r'^pm_chart/delete/(?P<id>\d+)$', views.chartdelete, name='chartdelete'),

    url(r'^dashboard/$', views.dashindex, name='dashindex'),
    url(r'^dashboard/add/$', views.dashadd, name='dashadd'),
    url(r'^dashboard/add/create$', views.dashcreate, name='dashcreate'),
    url(r'^dashboard/edit/(?P<id>\d+)$', views.dashedit, name='dashedit'),
    url(r'^dashboard/edit/update/(?P<id>\d+)$', views.dashupdate, name='dashupdate'),
    url(r'^dashboard/delete/(?P<id>\d+)$', views.dashdelete, name='dashdelete'),

    url(r'^consume/$', views.conindex, name='conindex'),
    url(r'^consume/add/$', views.conadd, name='conadd'),
    url(r'^consume/add/create$', views.concreate, name='concreate'),
    url(r'^consume/edit/(?P<id>\d+)$', views.conedit, name='conedit'),
    url(r'^consume/edit/update/(?P<id>\d+)$', views.conupdate, name='conupdate'),
    url(r'^consume/delete/(?P<id>\d+)$', views.condelete, name='condelete'),
]

myproject/myproject/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index_redirect, name='index_redirect'),
    url(r'^myapp/', include('myapp.urls')),
    url(r'^admin/', admin.site.urls),
]

myproject/myapp/models.py
from django.db import models
from django.core.validators import RegexValidator

alphaSpaces = RegexValidator(r'^[a-zA-Z ]+$','Only letters and spaces are allowed')
Numerics = RegexValidator(r'\+?\d[\d -]{8,12}\d','Please enter valid contact number')
Number = RegexValidator(r'^[0-9]\d*(\.\d+)?$','Please Enter only Numbers')
alphanumeric = RegexValidator(r'^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')

ORM_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Select_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Spare_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
Nature_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
PO_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)
DONE_CHOICES = (
    ('Item1','Item1'),
    ('Item2', 'Item2'),
)



# Create your models here.
class Jobsheet_trace(models.Model):
		From_Date = models.DateField()
		To_Date = models.DateField()
		JobSheet_No = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])

class Jobsheet(models.Model):
		Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		JobSheet_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Type = models.CharField(max_length=100, validators=[alphanumeric])
		In_Date = models.DateField()
		Expt_Date = models.DateField()
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		Vehicle = models.CharField(max_length=100, validators=[alphanumeric])
		Out_Date = models.DateField()
		Trailor = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Additional_KM = models.CharField(max_length=100, validators=[alphanumeric])
		Owner = models.CharField(max_length=100, validators=[alphanumeric])
		Tyre_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Maintenance_Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		Total_KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])
		pendding_Remark = models.CharField(max_length=100, validators=[alphanumeric])
		Store = models.CharField(max_length=100, validators=[alphanumeric])
		Close_Date = models.DateField()
		JobSheet_No_List1 = models.CharField(verbose_name=("JobSheet No List"),max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		OutDate = models.DateField()
		KM_Reading1 = models.CharField(verbose_name=("KM Reading"), max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Check_list_Template = models.CharField(max_length=100, validators=[alphanumeric])

class OMR(models.Model):
		Vehicle_No = models.CharField(max_length=50, validators=[alphanumeric])
		OMR_No_List = models.CharField(max_length=100, validators=[alphanumeric])
		Office_list = models.CharField(max_length=100,  validators=[alphanumeric])
		Date = models.DateField()
		OMR_No = models.CharField(max_length=100, validators=[alphanumeric])
		ORM_Type = models.CharField(max_length=100, choices=ORM_CHOICES,)
		Spare_Group = models.CharField(max_length=100, validators=[alphanumeric])
		Completion_Date = models.DateField()
		ORM_Nature = models.CharField(max_length=100, validators=[alphanumeric])
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=100, validators=[alphanumeric])
		Driver = models.CharField(max_length=100, validators=[alphanumeric])
		Place = models.CharField(max_length=100, validators=[alphanumeric])
		Supervisor = models.CharField(max_length=100, validators=[alphanumeric])
		On_Road_Date = models.DateField()
		Trip_Detail = models.CharField(max_length=100, validators=[alphanumeric])
		Approx_Amount = models.CharField(max_length=100, validators=[alphanumeric])
		Remarks = models.CharField(max_length=100, validators=[alphanumeric])
		Comment = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Date = models.DateField()
		Verified_By = models.CharField(max_length=100, validators=[alphanumeric])
		Varification_Remarks = models.CharField(max_length=100, validators=[alphanumeric])

class Part_Tracker(models.Model):
		Type = models.CharField(max_length=100, choices=Select_CHOICES,)
		SNo = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_No = models.CharField(max_length=100, validators=[alphanumeric])
		Doc_Date = models.DateField()
		CR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		DR_AC = models.CharField(max_length=100, validators=[alphanumeric])
		Status = models.CharField(max_length=100, validators=[alphanumeric])
		Trail_Status = models.CharField(max_length=100, validators=[alphanumeric])
		Card_No = models.CharField(max_length=100, validators=[alphanumeric])
		Life = models.CharField(max_length=100, validators=[alphanumeric])
		S = models.BooleanField(max_length=100, validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Reading = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		Purchase_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		TP_Coast = models.CharField(max_length=100, validators=[alphanumeric])
		Scrap_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Est_Cost = models.CharField(max_length=100, validators=[alphanumeric])
		Reason = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Chart(models.Model):
		SNo = models.CharField(max_length=50, validators=[alphanumeric])
		Date = models.DateField()
		Inactive_Date = models.DateField()
		Class_Name = models.CharField(max_length=100, validators=[alphanumeric])
		PM_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Days = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Run = models.CharField(max_length=100, validators=[alphanumeric])
		KM_Alert = models.CharField(max_length=100, validators=[alphanumeric])
		Map_Next_PM = models.CharField(max_length=100, validators=[alphanumeric])
		Remark = models.CharField(max_length=100, validators=[alphanumeric])

class PM_Master(models.Model):
		Preventive_list = models.CharField(max_length=100, validators=[alphanumeric])
		Preventive_Name = models.CharField(max_length=100, validators=[alphanumeric])
		Spare_Group = models.CharField(max_length=100, choices=Spare_CHOICES,)
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Description = models.CharField(max_length=200, validators=[alphanumeric])


class Repair_Dashboard(models.Model):
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No = models.CharField(max_length=100, validators=[alphanumeric])
		Jobsheet_no = models.CharField(max_length=100, validators=[alphanumeric])
		InDate = models.DateField()
		Expected_Date = models.DateField()
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"), max_length=200, validators=[alphanumeric])
		Driver_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		Supervisor_Name =  models.CharField(max_length=100,  validators=[alphanumeric])
		OutDate = models.DateField()

class Repair_Consume(models.Model):
		Nature = models.CharField(max_length=100, choices=Nature_CHOICES,)
		Vehicle_No1 = models.CharField(verbose_name=("Vehicle No"),max_length=100,  validators=[alphanumeric])
		Supplier = models.CharField(max_length=100, validators=[alphanumeric])
		Consume_Search = models.CharField(max_length=100, validators=[alphanumeric])
		Office = models.CharField(max_length=100,  validators=[alphanumeric])
		Supplier1 = models.CharField(verbose_name=("Supplier"), max_length=200, validators=[alphanumeric])
		PO_Type = models.CharField(max_length=100, choices=PO_CHOICES,)
		Narration =  models.CharField(max_length=100,  validators=[alphanumeric])
		Document_Date = models.DateField()
		Voucher_Date = models.DateField()
		Document_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vendor_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Vehicle_No =  models.CharField(max_length=100,  validators=[alphanumeric])
		Expense_AC = models.CharField(max_length=100,  validators=[alphanumeric])
		Ref =  models.CharField(verbose_name=("Ref / PONo"), max_length=100,  validators=[alphanumeric])
		Labour_Code = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Qty = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Rate = models.CharField(max_length=100,  validators=[alphanumeric])
		Labour_Amount = models.CharField(max_length=100,  validators=[alphanumeric])
		DoneBy = models.CharField(max_length=100, choices=DONE_CHOICES,)
		Labour_Remark = models.CharField(max_length=100,  validators=[alphanumeric])

myproject/myapp/templates/pm_chart/change.html
{% extends 'base.html' %}
{% block body %}
<h3 class="text-primary" style="text-align: center;">PM Chart Registration</h3>
    <hr style="border-top:1px dotted #000;"/>
    {% if members5 %}
    <form method="POST" action="update/{{ members5.id }}">
        {% else %}
        <form class=""  action="create" method="POST">
    {% endif %}
        {% csrf_token %}
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_SNo" class="form-group"> <label for="id_SNo" class="control-label  requiredField">
                SNo<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.SNo }}" name="SNo" maxlength="50" class="textinput textInput form-control" required id="id_SNo" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Date" class="form-group"> <label for="id_Date" class="control-label  requiredField">
                Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members5.Date|date:'Y-m-d' }}" name="Date" class="datepicker dateinput form-control" required id="id_Date" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Inactive_Date" class="form-group"> <label for="id_Inactive_Date" class="control-label  requiredField">
                Inactive Date<span class="asteriskField">*</span> </label> <div class="controls "> <input type="date" value="{{ members5.Inactive_Date|date:'Y-m-d' }}" name="Inactive_Date" class="datepicker dateinput form-control" required id="id_Inactive_Date" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Class_Name" class="form-group"> <label for="id_Class_Name" class="control-label  requiredField">
                Class Name<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.Class_Name }}" name="Class_Name" maxlength="100" class="textinput textInput form-control" required id="id_Class_Name" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_PM_Name" class="form-group"> <label for="id_PM_Name" class="control-label  requiredField">
                PM Name<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.PM_Name }}" name="PM_Name" maxlength="100" class="textinput textInput form-control" required id="id_PM_Name" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Days" class="form-group"> <label for="id_Days" class="control-label  requiredField">
                Days<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.Days }}" name="Days" maxlength="100" class="textinput textInput form-control" required id="id_Days" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_KM_Run" class="form-group"> <label for="id_KM_Run" class="control-label  requiredField">
                KM Run<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.KM_Run }}" name="KM_Run" maxlength="100" class="textinput textInput form-control" required id="id_KM_Run" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_KM_Alert" class="form-group"> <label for="id_KM_Alert" class="control-label  requiredField">
                KM Alert<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.KM_Alert }}" name="KM_Alert" maxlength="100" class="textinput textInput form-control" required id="id_KM_Alert" /> </div> </div> </div>

</div>
<div  
    class="row" > <div  
    class="col-md-3" > <div id="div_id_Map_Next_PM" class="form-group"> <label for="id_Map_Next_PM" class="control-label  requiredField">
                Map Next PM<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.Map_Next_PM }}" name="Map_Next_PM" maxlength="100" class="textinput textInput form-control" required id="id_Map_Next_PM" /> </div> </div> </div>
<div  
    class="col-md-3" > <div id="div_id_Remark" class="form-group"> <label for="id_Remark" class="control-label  requiredField">
                Remark<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" value="{{ members5.Remark }}" name="Remark" maxlength="100" class="textinput textInput form-control" required id="id_Remark" /> </div> </div> </div>

</div>
<!--         <div class="form-group">
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" value="{{ members5.firstname }}" required="required"/>
        </div>
        <div class="form-group">
            <label for="lastname">Lastname</label>
            <input type="text" name="lastname" value="{{ members.lastname }}" required="required"/>
        </div> -->
            {% if members5 %}
    <div class="form-group">
            <button type="submit" class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-edit"></span></button>
        </div>
        {% else %}
        <button type="submit" class="btn btn-sm btn-primary">save<span class="glyphicon glyphicon-plus" style="margin-left: 7px;"></span></button>
    {% endif %}
    <a class="btn btn-sm btn-danger" href="../">Cancel<span class="glyphicon glyphicon-remove" style="margin-left: 7px;"></span></a>
    </form>
{% endblock %}

myproject/myapp/templates/pm_chart/index.html
{% extends 'base.html' %}
{% block body %}
<style>
table {
        /*display: block;*/
        overflow-x: auto;
        white-space: nowrap;
    }
</style>
<h3 class="text-primary" style="text-align: center;">Part Tracker Registration</h3>
<hr style="border-top:1px dotted #000;"/>
<div class="container" style="text-align: center;">
    <a class="btn btn-sm btn-primary" href="add/{{ member2.id }}">New Entry<span class="glyphicon glyphicon-plus" style="margin-left: 7px;"></span></a>
</div>
<hr style="border-top:1px dotted #000;"/>
<table class="table table-bordered" id="example" class="display" cellspacing="0" width="100%">
    <thead class="alert-warning">
        <tr>
            <th>SNo</th>
            <th>Date</th>
            <th>Inactive_Date</th>
            <th>Class_Name</th>
            <th>PM_Name</th>
            <th>Days</th>
            <th>KM_Run</th>
            <th>KM_Alert</th>
            <th>Map_Next_PM</th>
            <th>Remark</th>   
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for member5 in members5 %}
        <tr>
            <td>{{ member5.SNo }}</td>
            <td>{{ member5.Date }}</td>
            <td>{{ member5.Inactive_Date }}</td>
            <td>{{ member5.Class_Name }}</td>
            <td>{{ member5.PM_Name }}</td>
            <td>{{ member5.Days }}</td>
            <td>{{ member5.KM_Run }}</td>
            <td>{{ member5.KM_Alert }}</td>
            <td>{{ member5.Map_Next_PM }}</td>
            <td>{{ member5.Remark }}</td>
            <td><center><a class="btn btn-sm btn-warning" href="edit/{{ member5.id }}"><span class="glyphicon glyphicon-edit"></span></a> <a class="btn btn-sm btn-danger" href="delete/{{ member5.id }}"><span class="glyphicon glyphicon-trash"></span></a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}